### ISSUE TITLE
Error regarding 'Tooltip' in tooltip.py

### ISSUE THREAD

**Issue by tperenboom** [j4321/tkFileBrowser#14]
Hi, great and useful module!

I'm getting an error message when running any of the functions in tkfilebrowser (Python 3.6 on Windows, tkinter version 8.6.6 running in a Conda environment), and the cause is in tooltip.py. If this script is left unaltered, the following error message is printed:

Traceback (most recent call last):
  File "main.py", line 30, in <module>
    input_images = askopendirnames(title='Select folders with input images', initialdir=dropbox_dir)
  File "C:\...\lib\site-packages\tkfilebrowser\functions.py", line 65, in askopendirnames
    title=title, **kwargs)
  File "C:\...\lib\site-packages\tkfilebrowser\filebrowser.py", line 272, in __init__
    wrapper = TooltipTreeWrapper(self.left_tree)
  File "C:\Users\...\lib\site-packages\tkfilebrowser\tooltip.py", line 85, in __init__
    self.tooltip = Tooltip(tree, **kwargs)
  File "C:\Users\...\lib\site-packages\tkfilebrowser\tooltip.py", line 43, in __init__
    self.attributes('-type', 'tooltip')
  File "C:\Users\...\lib\tkinter\__init__.py", line 1785, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: wrong # args: should be "wm attributes window ?-alpha ?double?? ?-transparentcolor ?color?? ?-disabled ?bool?? ?-fullscreen ?bool?? ?-toolwindow ?bool?? ?-topmost ?bool??"

This problem is solved if I comment out line 43 (self.attributes('-type', 'tooltip')) in tooltip.py.

**Comment by j4321** [comment]
Hello,

I designed this module for Linux and never tried it in Windows and I am aware that `.attributes('-type', ...)` is Linux-specific. The reason why I did not make a cross-platform module is that in my opinion tkinter default filedialogs for Windows are not so bad compared to the Linux ones. As far as I remember (I don't use Windows much) they are quite similar to WIndows Explorer while I tried to copy  the look and feel of thunar / zenity to make my module. 

However, if you confirm that except for the `self.attributes('-type', 'tooltip')` line in `tooltip.py` the module works fine in Windows and you are interested in using it, I can make it cross-platform.

**Comment by tperenboom** [comment]
The functions 'askopendirname(s)' and 'askopenfilename(s)' work perfectly fine without that line, I really like the fuctionality of multiple selection that is not readily available in tkinter's filedialog (as far as I'm aware).

So, if you would be willing to make the module cross-platform I'm sure more users would really appreciate your effort!
