### ISSUE TITLE
FileBrowser doesn't show networked drives on Windows

### ISSUE THREAD

**Issue by ivanlan9** [j4321/tkFileBrowser#16]
This is a very easy fix:

About line 329 in FileBrowser.py, changed the line that reads

   devices = psutil.disk_partitions()

to

   devices = psutil.disk_partitions(all=True if OSNAME=="nt" else False)

Once this is done, mapped network drives on Windows show up properly.  You don't want all=True on Linux, as that would get a bunch of non-useful items ('/sys/kernel/debug' and so on).

**Comment by j4321** [comment]
Thanks for the report and the fix, I am not using Windows so I was not aware of the issue.
