### ISSUE TITLE
Current Example on Github uses 2.4 which is the latest version, but PyPi is 2.3.2

### ISSUE THREAD

**Issue by mike-sosa-sofarocean** [j4321/tkFileBrowser#21]
Can you update PyPi to the latest release. Thanks!

**Comment by j4321** [comment]
The latest release is 2.3.2, see the [Releases tab in github](https://github.com/j4321/tkFileBrowser/releases). I did add a 2.4.0 entry in the README to update the changelog each time I merge a branch in the master one to keep track of changes. However, you will notice that I haven't bumped the version yet in setup.py. I will put version 2.4.0 on Pypi once it is officially released on Github which is not the case right now.

I will try to do it during the Christmas holidays but I would like to give a try at #19 before publishing the release.

**Comment by nahsimai** [comment]
Hey, sorry for commenting on a closed issue, but could you please update the release now. I am working on a project where having the openpathname function would be pretty useful. 

Btw, thanks for this browser. So much better than the default one from tkinter.
